"""
citation_service.py - Process and build structured citations from LLM responses

Parses LLM answer text to find references like [Source 1], [Source 2]
and maps them back to the original code chunks returned by retrieval_service.
"""

import re
from app.models.responses import Citation
from app.utils.logger import get_logger

logger = get_logger(__name__)

# File extension to syntax highlighter language mapping
_EXTENSION_LANG_MAP = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "jsx",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".java": "java",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".swift": "swift",
    ".kt": "kotlin",
    ".scala": "scala",
    ".r": "r",
    ".lua": "lua",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    ".ps1": "powershell",
    ".sql": "sql",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".less": "less",
    ".xml": "xml",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "ini",
    ".md": "markdown",
    ".rst": "restructuredtext",
    ".dockerfile": "dockerfile",
    ".makefile": "makefile",
}


def _detect_language(file_path: str) -> str:
    """Detect programming language from file path extension."""
    import os
    _, ext = os.path.splitext(file_path.lower())

    # Special filename checks
    basename = os.path.basename(file_path.lower())
    if basename == "dockerfile":
        return "dockerfile"
    if basename == "makefile":
        return "makefile"
    if basename in (".env", ".env.example"):
        return "bash"

    return _EXTENSION_LANG_MAP.get(ext, "text")



def extract_citations(
    answer: str,
    retrieved_chunks: list[dict],
) -> list[Citation]:
    """
    Scan LLM answer for inline citation patterns and build structured Citation objects.

    Looks for patterns like '[Source 1]' or '[Source 2]' and matches them with the
    correct retrieved chunk (1-indexed matching retrieved_chunks list).

    Args:
        answer: The text response generated by the LLM
        retrieved_chunks: The list of raw results from retrieval_service

    Returns:
        List of unique Citation Pydantic models referenced in the answer
    """
    # Find all patterns of '[Source N]' or '[Source N: ...]'
    pattern = r"\[Source\s+(\d+)\]"
    matches = re.findall(pattern, answer, re.IGNORECASE)

    # Convert matches to integer indices (1-indexed to 0-indexed)
    source_numbers = sorted(list(set(int(m) for m in matches)))
    citations = []

    for num in source_numbers:
        # Check if the source number corresponds to an actual retrieved chunk
        chunk_idx = num - 1
        if 0 <= chunk_idx < len(retrieved_chunks):
            chunk = retrieved_chunks[chunk_idx]

            # Determine confidence indicator
            score = chunk.get("score", 0.0)
            if score >= 0.85:
                confidence = "high"
            elif score >= 0.70:
                confidence = "medium"
            else:
                confidence = "low"

            # Return full chunk content for syntax-highlighted preview
            full_content = chunk.get("content", "")

            # Auto-detect language from file extension
            file_path = chunk.get("file_path", "unknown")
            language = _detect_language(file_path)

            citation = Citation(
                source_number=num,
                file_path=file_path,
                start_line=chunk.get("start_line", 0),
                end_line=chunk.get("end_line", 0),
                content_preview=full_content,
                language=language,
                relevance_score=score,
                confidence=confidence,
            )
            citations.append(citation)

    logger.info(f"Extracted {len(citations)} citations from LLM response")
    return citations
